### PR TITLE
Add support for client TLS certificates/keys

### LINKED ISSUE #4: Support for client certificates / mutual TLS
Hi there. Are there any plans or interest in supporting mutual TLS authentication?

I might be interested in contributing if that's not outside the scope of the project.

Cheers.

### PR DESCRIPTION
**Pull request by nrhtr**
Fixes #4 

Let me know if anything needs changing / fixing.

### CODE REVIEW

**Comment by nrhtr** [comment]
@dustinmiller @mikemrm Is anyone able to review this? Thanks.

**Comment by dustinmiller** [comment]
lgtm :shipit:

**Review by dustinmiller — APPROVED** [review]

**Comment by nrhtr** [comment]
Is it possible to get this merged? Thanks.

**Comment by mmlb** [comment]
Don't think this is needed anymore, any nacks against closing?

**Pull request closed without merging**
