### PR TITLE
FS-1291: Add lsblk version to JSON, in a compatible way

### PR DESCRIPTION
**Pull request by ofaurax**
I add the tool to the JSON data of each disks, so that the output of lsblk is still a disks list

### CODE REVIEW

**Comment by luke-jarymowycz** [comment]
Output looks good in local testing.

   "lsblk": {
      "name": "/dev/sdd",
      "serial": "PHYF046100ZW240AGN",
      "model": "INTEL SSDSC2KB24",
      "size": 240057409536,
      "rev": "0132",
      "rota": false,
      "vendor": "ATA     ",
      "tool": "lsblk from util-linux 2.37.2"
    }

**Review by luke-jarymowycz — APPROVED** [review]
approved

**Comment by ofaurax** [comment]
> "size": 240057409536,
> ...
> "rota": false, 
> ...
> "tool": "lsblk from util-linux 2.37.2"

For the record, typical use should output util-linux 2.27, with size and rota being strings and not number/boolean

**Comment by mmlb** [comment]
This feels like it returns very weird output. Here's what I'm getting when I run this locally:
```
root@6b9e4815e9ec:/home/manny/projects/github.com/packethost/packet-hardware/packethardware# python -c 'import utils; import json; print(json.dumps(utils.lsblk()))'|jq -S
cmd="lsblk -b -J -p -o NAME,SERIAL,MODEL,SIZE,REV,ROTA,VENDOR", klass="utils", method="cmd_output"
cmd="lsblk -V", klass="utils", method="cmd_output"
[
  [
    {
      "model": null,
      "name": "/dev/loop0",
      "rev": null,
      "rota": false,
      "serial": null,
      "size": 2147483648,
      "vendor": null
    },
    {
      "children": [
        {
          "model": null,
          "name": "/dev/sda1",
          "rev": null,
          "rota": false,
          "serial": null,
          "size": 1073741824,
          "vendor": null
        },
        {
          "model": null,
          "name": "/dev/sda2",
          "rev": null,
          "rota": false,
          "serial": null,
          "size": 479028314112,
          "vendor": null
        }
      ],
      "model": "MZ7LH480HBHQ0D3 ",
      "name": "/dev/sda",
      "rev": "HG58",
      "rota": false,
      "serial": null,
      "size": 480103981056,
      "vendor": "ATA     "
    },
    {
      "children": [
        {
          "model": null,
          "name": "/dev/sdb1",
          "rev": null,
          "rota": false,
          "serial": null,
          "size": 1073741824,
          "vendor": null
        },
        {
          "model": null,
          "name": "/dev/sdb2",
          "rev": null,
          "rota": false,
          "serial": null,
          "size": 479028314112,
          "vendor": null
        }
      ],
      "model": "MZ7LH480HBHQ0D3 ",
      "name": "/dev/sdb",
      "rev": "HG58",
      "rota": false,
      "serial": null,
      "size": 480103981056,
      "vendor": "ATA     "
    },
    {
      "model": "MTFDDAV240TDU   ",
      "name": "/dev/sdc",
      "rev": "J004",
      "rota": false,
      "serial": null,
      "size": 240057409536,
      "vendor": "ATA     "
    },
    {
      "model": "MTFDDAV240TDU   ",
      "name": "/dev/sdd",
      "rev": "J004",
      "rota": false,
      "serial": null,
      "size": 240057409536,
      "vendor": "ATA     "
    },
    {
      "model": null,
      "name": "/dev/zram0",
      "rev": null,
      "rota": false,
      "serial": null,
      "size": 33503051776,
      "vendor": null
    }
  ],
  "lsblk from util-linux 2.38.1"
]
```

It feels weird to just dump a string as the last member of the array, but I guess there's not really a better option. I thought of "string at the beginning" instead of end but thats not much of a win (except that it can sort of be used to change the parser in EMAPI land if necessary). The other thought is `{"meta":{"tool version":"...", "schema":"v1",...}}` as the first member in the array to be able to version the data.

**Comment by ofaurax** [comment]
`lsblk()` now outputs the disk data AND the tool version

**Comment by mmlb** [comment]
Right, and this is an internal method that is called by the Disk class and transformed appropriately (though incomplete in this PR, fixed in https://github.com/packethost/packet-hardware/pull/70).

**Pull request merged**
